/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.concordiarpg;

/**
 *
 * @author office Heros
 */
public class CampusMap extends javax.swing.JFrame {

    /**
     * Creates new form CampusMap
     */
    public CampusMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalet\\OneDrive\\Desktop\\Concordia RPG by Office Heroes\\CS Images\\Section 1.PNG")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 100, 280, 550);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 0, 0));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(1230, 280, 60, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalet\\OneDrive\\Desktop\\Concordia RPG by Office Heroes\\CS Images\\Sectoin 2.PNG")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(490, 550, 130, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalet\\OneDrive\\Desktop\\Concordia RPG by Office Heroes\\CS Images\\Section 3.PNG")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 420, 310, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalet\\OneDrive\\Desktop\\Concordia RPG by Office Heroes\\CS Images\\Section 4.PNG")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(610, 220, 320, 520);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 0, 0));
        jLabel7.setText("Campus Map");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 10, 190, 60);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(950, 10, 310, 770);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(1210, 10, 0, 240);

        jButton1.setBackground(new java.awt.Color(128, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Interactive Study");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(390, 170, 140, 30);

        jButton2.setBackground(new java.awt.Color(128, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Detail Study ");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(390, 220, 140, 30);

        jButton3.setBackground(new java.awt.Color(128, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear Detail");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(390, 270, 140, 30);

        jButton4.setBackground(new java.awt.Color(128, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back Home");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(390, 340, 140, 30);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(1210, 330, 250, 200);

        jLabel10.setBackground(new java.awt.Color(255, 204, 204));
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 150, 160, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HomePage Hp = new HomePage();
        Hp.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CampusMap Cm = new CampusMap();
        Cm.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jLabel9.setIcon(new javax.swing.ImageIcon("..\\images\\Label.PNG")); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(1210, 330, 250, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon("..\\images\\Descriptions.PNG")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(950, 10, 310, 770);

        jLabel8.setIcon(new javax.swing.ImageIcon("..\\images\\Descriptions2.PNG")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(1210, 10, 249, 240);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 0, 0));
        jLabel3.setText("Label");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(1230, 280, 60, 40);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jTextPane9 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        
        jScrollPane9.setViewportView(jTextPane10);

        jPanel2.add(jScrollPane9);
        jScrollPane9.setBounds(10, 340, 110, 90);
        jTextPane10.setText("Fjelsted Hall: Seniors, cultures, and safe space for students, and a chill hall. ");


        jTextPane9.setText("Bogs: Enjoy living in on-campus apartments, with a coffee shop just across the street, and have a quiet surrounding.");
        jPanel2.add(jTextPane9);
        jTextPane9.setBounds(210, 50, 240, 60);
        jTextPane9.setText("Bogs: Enjoy living in on-campus apartments, with a coffee shop just across the street, and have a quiet surrounding.");

        
        jScrollPane8.setViewportView(jTextPane8);

        jPanel2.add(jScrollPane8);
        jScrollPane8.setBounds(60, 240, 200, 90);
        jTextPane8.setText("Knutson Campus Center: Fill your college life with food, fun and knowledge here. You will be in here a lot of the time during the semester. ");

        
        jScrollPane7.setViewportView(jTextPane7);

        jPanel2.add(jScrollPane7);
        jScrollPane7.setBounds(40, 500, 180, 118);
        jTextPane7.setText("Olin Center: Theaters and artworks in the building.");

        
        jScrollPane6.setViewportView(jTextPane6);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(290, 440, 140, 120);
        jTextPane6.setText("Integrated Science Center: As the name applies, Science people come here. A high tech and good studying spot on campus.");

        
        jScrollPane3.setViewportView(jTextPane3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(560, 160, 190, 80);
        jTextPane3.setText("East Complex: Staying with Business students, athletes and parties with a Business Center filled with good technologies. ");
        

        jScrollPane2.setViewportView(jTextPane2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(800, 260, 180, 70);
        jTextPane2.setText("Townhouses: Enjoy living in on-campus apartments and attending classes by walking nearby. ");

        
        jScrollPane1.setViewportView(jTextPane1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(760, 420, 210, 80);
        jTextPane1.setText("Jake Christiansen Stadium: You can enjoy Concordia Football Team play. In HomeComing, you will have the stadium packed. ");

        jScrollPane4.setViewportView(jTextPane4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(70, 650, 230, 80);
        jTextPane4.setText("Olson Forum and Memorial Hall: From Beanie toss to enjoying gyms, and sports to swimming pool, certainly a place for staying fit and fun. ");

        jScrollPane5.setViewportView(jTextPane5);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(310, 690, 180, 100);
        jTextPane5.setText("Welcome Center: Welcome to Concordia College. Filled with incoming students and have a chat with admission officers you talked with when you applied. ");

        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampusMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampusMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampusMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampusMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
             public void run() {
              new CampusMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
   private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    
}
