/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.concordiarpg;

/**
 *
 * @author Office Heros
 */
public class LoginPage extends javax.swing.JFrame {

        
        
    
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPannel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 0, 0));
        jLabel1.setText("Password :");
        MainPannel.add(jLabel1);
        jLabel1.setBounds(140, 230, 100, 50);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 0, 0));
        jLabel2.setText("User name :");
        MainPannel.add(jLabel2);
        jLabel2.setBounds(130, 190, 100, 50);

        jButton1.setBackground(new java.awt.Color(215, 210, 25));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(128, 0, 0));
        jButton1.setText("Sign In");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        MainPannel.add(jButton1);
        jButton1.setBounds(380, 400, 90, 30);

        jPasswordField1.setBackground(new java.awt.Color(215, 219, 51));
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MainPannel.add(jPasswordField1);
        jPasswordField1.setBounds(230, 240, 170, 30);

        jTextField1.setBackground(new java.awt.Color(215, 219, 51));
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        MainPannel.add(jTextField1);
        jTextField1.setBounds(230, 200, 170, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        MainPannel.add(jLabel3);
        jLabel3.setBounds(230, 270, 220, 30);

        jLabel4.setForeground(new java.awt.Color(128, 0, 0));
        MainPannel.add(jLabel4);
        jLabel4.setBounds(300, 310, 110, 20);

        bk.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalet\\OneDrive\\Desktop\\Concordia RPG by Office Heroes\\CS Images\\LoginPageImg.jpg")); // NOI18N
        bk.setText("jLabel5");
        MainPannel.add(bk);
        bk.setBounds(0, 0, 600, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Here below were we stored the limited usernames with there respect passwords
        
        String email = jTextField1.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        
        String email1 = "jtesgera@cord.edu";
        String pass1 = "abcd1234";
          
        String email2 = "ywin@cord.edu";
        String pass2 = "1234abcd";
          
        String email3 = "stulujr@cord.edu";
        String pass3 = "a1b2c3d4"; 
        
        String email4 = "dlampl@cord.edu";
        String pass4 = "DarthVader"; 
        int countwrong = 0;
         
        
        // This is where we match the usernames and password with repect to the stored username and password 
        
         if ( ((email.equals(email1)) && (pass.equals(pass1))) || ((email.equals(email2)) && (pass.equals(pass2))) || ((email.equals(email3)) && (pass.equals(pass3))) || ((email.equals(email4)) && (pass.equals(pass4))) ) {
         
         HomePage Hp = new HomePage();
         Hp.setVisible(true);
         dispose();
         
         
         }
         
         
         else {
                 
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Incorrect Password. Please try again.");         // Shows this error when when the user inserts the wrong pass nword. 
        jLabel3.setBounds(230, 270, 220, 30);
         }
             
        countwrong += 1;
         
        if (countwrong == 1) {
                 
        jLabel4.setForeground(new java.awt.Color(128, 0, 0));
        jLabel4.setText("Forgot Password ?");
        jLabel4.setBounds(300, 310, 110, 20);   
        
        }
                 
             
         
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        

    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            
        
        
        
        
        
        
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPannel;
    private javax.swing.JLabel bk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
